version: "3.3"

services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: .
    depends_on:
      - db
    environment:
      DB_HOST: db
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: idotpet
